---
- name: run role
  hosts: "{{ host_list }}"
  # become: true
  roles:
    - createfile
  tasks:
    - name: Create the file
      file:
        path: /home/potest/example.txt
        state: touch
        owner: potest
        mode: "0644"
