---
- name: for file
  file:
    path: "{{ filename }}"
    state: touch
    owner: potest
    mode: "0644"
  failed_when: filename is defined

- name: for dir
  file:
    path: "{{ directoryname }}"
    state: directory
    owner: potest
    mode: "0644"
  failed_when: directoryname is not defined
  
- name: shell
  shell: 
    cmd: cat /home/potest/test
