---
- name: for file
  file:
    path: "{{ filename }}"
    state: touch
    owner: potest
    mode: "0644"
  when: filename is defined

- name: for dir
  file:
    path: "{{ directoryname }}"
    state: directory
    owner: potest
    mode: "0644"
  when: directoryname is defined
