---
- name: for file
  file:
    path: "{{ filename }}"
    state: touch
    owner: ansible
    mode: "0644"
  failed_when: filename is not defined

- name: for dir
  file:
    path: "{{ directoryname }}"
    state: directory
    owner: ansible
    mode: "0644"
  failed_when: directoryname is not defined
  
# - name: shell
#   shell: 
#     cmd: df -h | awk '$5 ~ /([9][1-9]|[0-9]{3,})%/ {print}'
#   register: x
- name: Check that the somefile.conf exists
  stat:
    path: "{{ filename }}"
  register: stat_result

- debug: stat_result
